name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  spotless:
    name: Spotless

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Java
        id: setup-jre
        uses: actions/setup-java@v1
        with:
          java-version: "18" # always use 18 for building
          architecture: x64

      - name: Set Test Java Runtime Environment variable
        run: echo "JAVA_TEST_HOME=${{ steps.setup-jre.outputs.path }}" >> $GITHUB_ENV

      - name: Spotless
        run: ./gradlew spotlessCheck

  build:
    name: Build and test

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "1.8"
          - "9"
          - "10"
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"
          - "18"

    steps:
      - uses: actions/checkout@master

      - name: Setup Test Java Runtime
        id: setup-test-jre
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64

      - name: Set Test Java Runtime Environment variable
        run: echo "JAVA_TEST_HOME=${{ steps.setup-test-jre.outputs.path }}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "18" # always use 18 for building
          architecture: x64

      - name: Tweak gradle.properties for Java 1.8
        if: ${{ matrix.java-version == '1.8' }}
        run: sed -e '/--add-exports/ s/^#*/#/' -i gradle.properties

      - name: Display version
        run: |
          ./gradlew --version
          echo "JAVA_TEST_HOME=$JAVA_TEST_HOME"

      - name: Build artifacts
        run: ./gradlew assemble generatePomFileForMavenJavaPublication javadoc

      - name: Start stripe-mock
        run: docker run -d -p 12111-12112:12111-12112 stripe/stripe-mock && sleep 5

      - name: Run test suite
        run: ./gradlew test

      - name: Send code coverage report to coveralls.io
        run: ./gradlew jacocoTestReport coveralls
        env:
          CI_NAME: github-actions
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: build/libs
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: maven
          path: build/publications/mavenJava/
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: javadoc
          path: build/docs/javadoc

  publish:
    #if: (github.event_name == 'push') && (startsWith(github.ref, 'refs/tags/v') && (endsWith(github.actor, '-stripe'))
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
      with:
        name: libs
        path: libs

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
      with:
        name: maven
        path: maven
